#include "port.h"

void port_init()
{
    // NC - Not Connected (not available in mcu package)
    // NR - Not routed (no routing to pin on pcb, floating)
    // NU - Not used (not currently in use)

    // Port A
    // PA00 - LO_ANA_PWR_EN
    // PA01 - TX_ANA_PWR_EN
    // PA02 - TX_PWR_VDET_DIV - PIOMUX B - (ADC - AIN 0)
    // PA03 - RX_PWR_VDET_DIV - PIOMUX B - (ADC - AIN 1)
    // PA04 - TX_RST
    // PA05 - RF_SPI_MISO - PIOMUX D - (SERCOM 0 - PAD 1)
    // PA06 - RF_SPI_MOSI - PIOMUX D - (SERCOM 0 - PAD 2)
    // PA07 - RF_SPI_SCK - PIOMUX D - (SERCOM 0 - PAD 3)
    // PA08 - DAC_I2C_SDA - PIOMUX D - (SERCOM 2 - PAD 0)
    // PA09 - DAC_I2C_SCL - PIOMUX D - (SERCOM 2 - PAD 1)
    // PA10 - nTX_SPI_CS
    // PA11 - LED
    // PA12 - NC
    // PA13 - NC
    // PA14 - EXT_IO_1_3
    // PA15 - EXT_IO_1_4
    // PA16 - MCU_I2C_SDA - PIOMUX C - (SERCOM 1 - PAD 0)
    // PA17 - MCU_I2C_SCL - PIOMUX C - (SERCOM 1 - PAD 1)
    // PA18 - MCU_SWO - PIOMUX D - (SERCOM 3 - PAD 2)
    // PA19 - RX_ANA_PWR_EN
    // PA20 - NC
    // PA21 - NC
    // PA22 - RX_DIG_PWR_EN
    // PA23 - TX_DIG_PWR_EN
    // PA24 - NR
    // PA25 - EXT_IO_1_5
    // PA26 - NC
    // PA27 - RX_RST
    // PA28 - nRX_SPI_CS
    // PA29 - NC
    // PA30 - SWCLK
    // PA31 - SWDIO
    PORT_REGS->GROUP[0].PORT_DIR = BIT(0) | BIT(1) | BIT(4) | BIT(6) | BIT(7) | BIT(10) | BIT(11) | BIT(18) | BIT(19) | BIT(22) | BIT(23) | BIT(27) | BIT(28);
    PORT_REGS->GROUP[0].PORT_OUT = BIT(8) | BIT(9) | BIT(10) | BIT(16) | BIT(17) | BIT(28) | BIT(30);
    PORT_REGS->GROUP[0].PORT_PINCFG[0] = 0;
    PORT_REGS->GROUP[0].PORT_PINCFG[1] = 0;
    PORT_PERI_MUX_SELECT(0, 2, 1);
    PORT_REGS->GROUP[0].PORT_PINCFG[2] = 0;
    PORT_PERI_MUX_SELECT(0, 3, 1);
    PORT_REGS->GROUP[0].PORT_PINCFG[3] = 0;
    PORT_REGS->GROUP[0].PORT_PINCFG[4] = 0;
    PORT_PERI_MUX_SELECT(0, 5, 3);
    PORT_REGS->GROUP[0].PORT_PINCFG[5] = PORT_PINCFG_INEN_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_PERI_MUX_SELECT(0, 6, 3);
    PORT_REGS->GROUP[0].PORT_PINCFG[6] = PORT_PINCFG_DRVSTR_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_PERI_MUX_SELECT(0, 7, 3);
    PORT_REGS->GROUP[0].PORT_PINCFG[7] = PORT_PINCFG_DRVSTR_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_PERI_MUX_SELECT(0, 8, 3);
    PORT_REGS->GROUP[0].PORT_PINCFG[8] = PORT_PINCFG_INEN_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_PERI_MUX_SELECT(0, 9, 3);
    PORT_REGS->GROUP[0].PORT_PINCFG[9] = PORT_PINCFG_INEN_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[10] = PORT_PINCFG_DRVSTR_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[11] = PORT_PINCFG_DRVSTR_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[14] = 0;
    PORT_REGS->GROUP[0].PORT_PINCFG[15] = 0;
    PORT_PERI_MUX_SELECT(0, 16, 2);
    PORT_REGS->GROUP[0].PORT_PINCFG[16] = PORT_PINCFG_DRVSTR_Msk | PORT_PINCFG_INEN_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_PERI_MUX_SELECT(0, 17, 2);
    PORT_REGS->GROUP[0].PORT_PINCFG[17] = PORT_PINCFG_DRVSTR_Msk | PORT_PINCFG_INEN_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_PERI_MUX_SELECT(0, 18, 3);
    PORT_REGS->GROUP[0].PORT_PINCFG[18] = PORT_PINCFG_DRVSTR_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[19] = 0;
    PORT_REGS->GROUP[0].PORT_PINCFG[22] = 0;
    PORT_REGS->GROUP[0].PORT_PINCFG[23] = 0;
    PORT_REGS->GROUP[0].PORT_PINCFG[24] = 0;
    PORT_REGS->GROUP[0].PORT_PINCFG[25] = 0;
    PORT_REGS->GROUP[0].PORT_PINCFG[27] = 0;
    PORT_REGS->GROUP[0].PORT_PINCFG[28] = PORT_PINCFG_DRVSTR_Msk;
    PORT_PERI_MUX_SELECT(0, 30, 6);
    PORT_REGS->GROUP[0].PORT_PINCFG[30] = PORT_PINCFG_INEN_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_PERI_MUX_SELECT(0, 31, 6);
    PORT_REGS->GROUP[0].PORT_PINCFG[31] = PORT_PINCFG_DRVSTR_Msk | PORT_PINCFG_INEN_Msk | PORT_PINCFG_PMUXEN_Msk;
}