name: Integrated mmWave Expantion board MCU firmware build tests

on:
  pull_request:
    paths:
      - "software/exp/mmw-int/**"
    branches: [ "v2" ]
  push:
    paths:
      - "software/exp/mmw-int/**"
    branches: [ "v2" ]
  workflow_dispatch:

env:
  ARM_LIBROOT: "/opt/arm-cmsis"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update install
      run:
        sudo apt-get update
      timeout-minutes: 5

    - name: Install toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1

    - name: Install build dependencies
      run: |
        # Install elfmem
        wget https://github.com/vankxr/elfmem/releases/download/2.0-0/elfmem_2.0-0_amd64.deb
        sudo dpkg -i elfmem_2.0-0_amd64.deb

        # Install Core pack
        git clone https://github.com/vankxr/Core-CMSIS
        cd Core-CMSIS/build
        chmod +x build.sh
        ./build.sh
        sudo mkdir -p $ARM_LIBROOT
        sudo mv ARM.CMSIS.5.9.0 $ARM_LIBROOT/ARM.CMSIS

        # Install SAMD21 pack
        sudo mkdir -p $ARM_LIBROOT/Microchip.SAMD21_DFP
        wget -O Microchip.SAMD21_DFP.3.6.144.zip https://packs.download.microchip.com/Microchip.SAMD21_DFP.3.6.144.atpack
        unzip Microchip.SAMD21_DFP.3.6.144.zip -d $ARM_LIBROOT/Microchip.SAMD21_DFP
      timeout-minutes: 5

    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        clean: true

    - name: Build integrated mmW Expantion MCU firmware
      run: |
        cd ${{github.workspace}}/software/exp/mmw-int
        make BUILD_TYPE=release

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: exp_mmw_int_firmware
        path: ${{github.workspace}}/software/exp/mmw-int/bin/v*
        retention-days: 30
